spring:
    application:
        name: HELLO_SPRING
    profiles:
            active: local
server:
    port: 9999
---
spring:
    config:
        activate:
            on-profile: local
sample:
    message: "Local message"
---
spring:
    config:
        activate:
            on-profile: stg
sample:
    message: ${MESSAGE}